### PR TITLE
Auto open first tab

### PR DESCRIPTION
**Pull request by miki131**

### CODE REVIEW

**Comment by RVxLab** [comment]
What problem are you aiming to solve with this?

**Comment by miki131** [comment]
I have a lot of tabs on user page which are relations and I don't want them open on page load but only when I click on tab myself

**Comment by RVxLab** [comment]
In the sense of lazy loading?

If so then this is a good idea! Can you rebase this please?

**Comment by miki131** [comment]
Done.

**Comment by miki131** [comment]
Could you please review and merge?

**Pull request merged**
