### PR TITLE
Nova gridder support

### PR DESCRIPTION
**Pull request by SpiritSaint**
Hi,

I receive a RFC in [nova-gridder](https://github.com/demency/nova-gridder/) repository (ref [issue](https://github.com/demency/nova-gridder/issues/1)). That package allows using Tailwind Grid System (Default nova tailwind version installed) to build better Nova UI.

This change allows using nova-gridder inside nova-tabs.

Check out this example:
picture

### CODE REVIEW

**Comment by demency** [comment]
Hi @bajramemini, can you check this MR please 🙏

**Comment by 949mac** [comment]
@bajramemini +1 for merge request

**Comment by RVxLab** [comment]
Sorry that it took so long for a response.

This looks like an excellent addition. I'll discuss this with bajramemini and get back to you.

**Review by RVxLab — APPROVED** [review]
Looks good!

Could you please rebase with the current master branch and add a section to the README about this then this can be merged.

Thanks for your PR!

**Comment by RVxLab** [comment]
Due to many changes that happened and the time passed I'm closing this PR.

I'll definitely look into adding this myself in a future update. Possibly 1.5 as I'm planning an overhaul of the Vue components.

**Pull request closed without merging**
