### PR TITLE
Fixed bottom margin on default search

### PR DESCRIPTION
**Pull request by feldsam**

### CODE REVIEW

**Comment by RVxLab** [comment]
Can you provide a screenshot of what this is supposed to fix?

**Comment by feldsam** [comment]
Screen Shot 2021-01-30 at 23 22 32
Screen Shot 2021-01-30 at 23 22 44

**Comment by RVxLab** [comment]
I see what you mean. Could you rebase with the current master?

**Comment by RVxLab** [comment]
Thanks for your PR 👍🏻

**Pull request merged**
