### PR TITLE
Fixes HasOne relationship not working in 2.2.1

### LINKED ISSUE #251: HasOne relationship not working in 2.2.1
Hello,

I get an error in the console when trying to use v2.2.1. Locking to 2.2.0 made it work again. See the error below:

image

Thank you!

### PR DESCRIPTION
**Pull request by crynobone**
fixes #251

### CODE REVIEW

**Comment by mstaack** [comment]
@marcfilipan can we get this released soon? thanks

**Comment by Ruitjes** [comment]
Would be nice if this could be merged! :)

**Comment by mateusgalasso** [comment]
Update please

**Comment by FrancoFourmantin** [comment]
@marcfilipan Would be great to merge this fix!! Thanks

**Comment by mstaack** [comment]
@marcfilipan please get this in. waiting for this with our internal release. thanks!

**Comment by mstaack** [comment]
thanks 👍🏼

**Pull request merged**
