### PR TITLE
Nova 2.9.2 compatiblity.

### PR DESCRIPTION
**Pull request by pbrisson**
Thanks for this package!

This fixes https://github.com/eminiarts/nova-tabs/issues/75.

### CODE REVIEW

**Comment by rikless** [comment]
Should add nova constraint on nova 2.9 version on this PR

**Comment by pbrisson** [comment]
It basically reverse those changes which aren't working for Nova 2.9.2: https://github.com/eminiarts/nova-tabs/pull/74

... which means it would work for anything Nova <> 2.9.0.

**Comment by rikless** [comment]
I may be wrong, bug 2.9 introduced a bug : https://github.com/eminiarts/nova-tabs/issues/73

So if this PR is just a rollback, then this bug will rollback too.

**Comment by pbrisson** [comment]
My PR was tested on Nova 2.9.2 with Nova Tabs 1.2.1. My point is that #73 and #74 are specific to Nova 2.9.0; seems all the method definitions discussed in #73 were fixed in Nova 2.9.2. For example, here's `rulesForUpdate` definition as of Nova 2.9.2:

```
    /**
     * Get the validation rules for a resource update request.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Laravel\Nova\Resource|null  $resource
     * @return array
     */
    public static function rulesForUpdate(NovaRequest $request, $resource = null)
    {
        $resource = $resource ?? new static(static::newModel());

        return static::formatRules($request, $resource->updateFields($request)
                    ->reject(function ($field) use ($request) {
                        return $field->isReadonly($request);
                    })
                    ->mapWithKeys(function ($field) use ($request) {
                        return $field->getUpdateRules($request);
                    })->all());
    }
```

... which is exactly what invalidates the fixes done in #74.

Therefore, that PR shouldn't be pinned to 2.9; it's the opposite. #74 should be pinned to 2.9.0, as changes it introduces will break any other version of Nova.

Makes sense? 😃

**Comment by rikless** [comment]
My bad ! Thank you !!

**Comment by bajramemini** [comment]
Thank you @pbrisson

**Pull request merged**
