### PR TITLE
Fix for #218

### PR DESCRIPTION
**Pull request by rderks88**
I made a mistake in earlier pull request. This should fix that.
Commented possibly a bit extensively, but thought it needed some clarification.

### CODE REVIEW

**Comment by jwerd** [comment]
I just pulled in @rderks88 changes and I'm getting this now: local.ERROR: Class "ConsultLive\Tabs\Tabs" not found {"userId":1,"exception":"[object] (Error(code: 0): Class \"ConsultLive\\Tabs\\Tabs\"

**Comment by jwerd** [comment]
@rderks88 make sure you are merging master from @eminiarts.  It says you are 35 commits behind.

**Comment by rderks88** [comment]
> @rderks88 make sure you are merging master from @eminiarts. It says you are 35 commits behind.

Excuse me, was focussed on the changes. Fetched upstream ✅

**Comment by jwerd** [comment]
@rderks88 

> > @rderks88 make sure you are merging master from @eminiarts. It says you are 35 commits behind.
> 
> Excuse me, was focussed on the changes. Fetched upstream ✅

Hey man, all good.  Checking out the changes and I'll let you know if this solves the issues for me.  Thanks!

**Comment by jwerd** [comment]
This is now working just fine for me. ✅

**Pull request merged**
