### PR TITLE
Fixed the deletion of a file

### PR DESCRIPTION
**Pull request by chinleung**
This PR fixes https://github.com/laravel/nova-issues/issues/1936 by updating the `updateFields` method in `Eminiarts\Tabs\TabsOnEdit` to return a `Eminiarts\Tabs\FieldCollection`, which extends `Laravel\Nova\Fields\FieldCollection` instead of a regular `Illuminate\Support\Collection` to have access to `findFieldByAttribute` method.

Also overwritten the method of `whereInstanceOf` to search through the fields in the tabs instead of the first level element.

### CODE REVIEW

**Comment by ibrunotome** [comment]
Hello @bajramemini, can you merge this to solve the bug on TabsOnEdit?

**Comment by bolechen** [comment]
Hello @bajramemini, can you merge this to solve the bug on TabsOnEdit?

**Comment by RVxLab** [comment]
Hey! Sorry it took this long for a response.

This has become quite a big PR, I'd need to have a look locally first.

**Comment by RVxLab** [comment]
This seems to have been fixed in #62 and #63, can you check with version 1.2.3 of this package?

**Comment by golonix** [comment]
I'm using Nova 3.14.0 and the issue still exists. With `FieldCollection` class from this MR, it works as expected.

**Comment by RVxLab** [comment]
@golonix Thanks for confirming this. I'll look into merging this soon.

**Comment by RVxLab** [comment]
Thanks for your PR :)

**Pull request merged**
