### PR TITLE
Updated ActionsInTabs trait to match latest Nova

### PR DESCRIPTION
**Pull request by feldsam**
Signed-off-by: Kristian Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by RVxLab** [comment]
Is there a related Nova issue or PR I could reference?

**Comment by feldsam** [comment]
Hi, from what I understand, you just overwriting nova method detailFlieds, which in meantime was updated.

https://github.com/laravel/nova/blob/a16711e1a7f7fb9372f70aa734100c055a0ed12f/src/ResolvesFields.php#L55

in the same file there is also method `actionfield`, which can be used instead of MorhMany in readme

**Comment by RVxLab** [comment]
Awesome, thank you.

I'll need some time to look into this. I'll get back to you. 

Also could you rebase with master?

**Comment by RVxLab** [comment]
Thanks for the PR!

**Pull request merged**
