### PR TITLE
Remove panelsWithDefaultLabel() from HasTabs trait

### PR DESCRIPTION
**Pull request by jwerd**
This method is preventing default Nova 4 functionality (such as showing the Action menu, edit button, etc)

### CODE REVIEW

**Comment by jwerd** [comment]
Added it back but reversed the order.  When we do not have components or tabs, we load the nova toolbar else we load the components and tabs.  Hopefully that solves this.

**Comment by rderks88** [comment]
I do seem to have made a mistake. But I doubt that this is the solution. I'm going to get back to you asap.

**Comment by rderks88** [comment]
@jwerd can you confirm #219 fixes your issue

Just to clarify:
My reason for original PR was that when using tabs only as a tab for showing tabbed relationships, the package hid the toolbar for the default nova4 panel that showed the attributes
#219 checks if the first panel is a tabs-component, if it is not, it forces the toolbar to apear for the default nova4 attributes panel.

**Comment by jwerd** [comment]
> @jwerd can you confirm #219 fixes your issue

I will check this later tonight and let you know.

**Comment by jwerd** [comment]
#219 solves our issues.

**Pull request closed without merging**
